languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Blowfish"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "che tema, Hugo."

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = " che tema, Hugo."
  bio = "che tema, Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]