languageCode = "en"
languageName = "English"
weight = 1
title = "Blowfish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "this is Hugo."

[params.author]
  name = "Blowfish"
  email = "nuno@n9o.xyz"
  image = "img/blowfish_logo.png"
  headline = "this is Hugo."
  bio = "this is Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]